// Frontend-only mock data for the admin dashboard.
// Keep this file close to realistic backend responses so the UI can be tested
// before the ASP.NET API is connected.

export const MOCK_ADMIN = {
  id: 'admin-1',
  firstName: 'Mohammed',
  lastName: 'Admin',
  phone: '+218911000001',
  email: 'admin@investly.ly',
  role: 'admin',
  type: 'individual',
  isActive: true,
  isBlocked: false,
  isVerified: true,
  walletBalance: 0,
  createdAt: '2026-01-10T09:00:00Z',
};

export const MOCK_SESSION = {
  token: 'mock-dev-admin-token',
  user: MOCK_ADMIN,
};

export const MOCK_USERS = [
  {
    id: 'u1',
    firstName: 'Ahmed',
    lastName: 'Ali',
    phone: '+218911111111',
    email: 'ahmed.investor@test.ly',
    role: 'investor',
    type: 'individual',
    isActive: true,
    isBlocked: false,
    isVerified: true,
    walletBalance: 7500,
    contributionTotal: 12000,
    contributionsCount: 4,
    createdAt: '2026-02-03T10:00:00Z',
  },
  {
    id: 'u2',
    firstName: 'Fatima',
    lastName: 'Hassan',
    phone: '+218922222222',
    email: 'fatima.owner@test.ly',
    role: 'owner',
    type: 'organization',
    isActive: true,
    isBlocked: false,
    isVerified: true,
    companyName: 'Tripoli Tech Ventures',
    projectsCount: 3,
    createdAt: '2026-02-20T12:30:00Z',
  },
  {
    id: 'u3',
    firstName: 'Omar',
    lastName: 'Mansour',
    phone: '+218933333333',
    email: 'omar.pending@test.ly',
    role: 'investor',
    type: 'individual',
    isActive: true,
    isBlocked: false,
    isVerified: false,
    walletBalance: 300,
    createdAt: '2026-03-08T08:20:00Z',
  },
  {
    id: 'u4',
    firstName: 'Sara',
    lastName: 'Khalil',
    phone: '+218944444444',
    email: 'sara.blocked@test.ly',
    role: 'owner',
    type: 'organization',
    isActive: true,
    isBlocked: true,
    isVerified: true,
    companyName: 'Green Build Libya',
    projectsCount: 1,
    deletedProjectsCount: 2,
    entrepreneurBlockedCount: 1,
    createdAt: '2026-01-18T11:15:00Z',
  },
];

export const MOCK_PROJECTS = [
  {
    id: 'p1',
    title: 'Smart Farming Platform',
    description: 'IoT sensors and analytics for Libyan farms.',
    category: 'agri',
    status: 'active',
    fundingGoal: 120000,
    currentAmount: 82000,
    minInvestment: 500,
    progress: 68,
    ownerId: 'u2',
    ownerName: 'Fatima Hassan',
    ownerCompanyName: 'Tripoli Tech Ventures',
    investorsCount: 18,
    viewsCount: 430,
    duration: 12,
    startDate: '2026-02-01T00:00:00Z',
    endDate: '2027-02-01T00:00:00Z',
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'p2',
    title: 'Solar Cold Storage',
    description: 'Solar-powered cold storage for small food suppliers.',
    category: 'energy',
    status: 'pending',
    fundingGoal: 250000,
    currentAmount: 0,
    minInvestment: 1000,
    progress: 0,
    ownerId: 'u2',
    ownerName: 'Fatima Hassan',
    ownerCompanyName: 'Tripoli Tech Ventures',
    investorsCount: 0,
    viewsCount: 76,
    createdAt: '2026-03-11T14:00:00Z',
  },
  {
    id: 'p3',
    title: 'Clinic Booking App',
    description: 'Booking, payments, and reminders for private clinics.',
    category: 'health',
    status: 'completed',
    fundingGoal: 90000,
    currentAmount: 90000,
    minInvestment: 250,
    progress: 100,
    ownerId: 'u4',
    ownerName: 'Sara Khalil',
    ownerCompanyName: 'Green Build Libya',
    investorsCount: 22,
    viewsCount: 610,
    createdAt: '2025-11-15T09:30:00Z',
  },
  {
    id: 'p4',
    title: 'Learning Marketplace',
    description: 'Arabic-first online courses for practical business skills.',
    category: 'edu',
    status: 'rejected',
    fundingGoal: 70000,
    currentAmount: 0,
    minInvestment: 200,
    progress: 0,
    ownerId: 'u4',
    ownerName: 'Sara Khalil',
    ownerCompanyName: 'Green Build Libya',
    investorsCount: 0,
    viewsCount: 120,
    createdAt: '2026-04-01T10:00:00Z',
  },
];

export const MOCK_INVESTMENTS = [
  {
    id: 'inv1',
    projectId: 'p1',
    projectTitle: 'Smart Farming Platform',
    reference: 'INV-2026-001',
    amount: 5000,
    fundingPercentage: 4.17,
    equityPercentage: 0.5,
    status: 'completed',
    investorId: 'u1',
    investorName: 'Ahmed Ali',
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'inv2',
    projectId: 'p3',
    projectTitle: 'Clinic Booking App',
    reference: 'INV-2026-002',
    amount: 7000,
    fundingPercentage: 7.78,
    equityPercentage: 0.9,
    status: 'completed',
    investorId: 'u1',
    investorName: 'Ahmed Ali',
    createdAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'inv3',
    projectId: 'p1',
    projectTitle: 'Smart Farming Platform',
    reference: 'INV-2026-003',
    amount: 1500,
    fundingPercentage: 1.25,
    equityPercentage: 0.15,
    status: 'pending',
    investorId: 'u3',
    investorName: 'Omar Mansour',
    createdAt: '2026-04-02T16:10:00Z',
  },
];

export const MOCK_PAYMENTS = [
  {
    id: 'pay1',
    amount: 5000,
    currency: 'LYD',
    method: 'wallet',
    status: 'completed',
    userId: 'u1',
    userName: 'Ahmed Ali',
    transactionId: 'TXN-2026-001',
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'pay2',
    amount: 1500,
    currency: 'LYD',
    method: 'wallet',
    status: 'pending',
    userId: 'u3',
    userName: 'Omar Mansour',
    transactionId: 'TXN-2026-002',
    createdAt: '2026-04-02T16:10:00Z',
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'n1',
    type: 'project',
    title: 'Project deletion warning',
    message: 'One project deletion has been recorded for this entrepreneur.',
    isRead: false,
    targetUserId: 'u4',
    createdAt: '2026-04-11T10:00:00Z',
  },
  {
    id: 'n2',
    type: 'system',
    title: 'Entrepreneur account blocked',
    message: 'This entrepreneur reached the project deletion limit.',
    isRead: false,
    targetUserId: 'u4',
    createdAt: '2026-04-12T10:00:00Z',
  },
  {
    id: 'n3',
    type: 'system',
    title: 'SMTP test ready',
    message: 'Use the admin email test endpoint after setting SMTP credentials.',
    isRead: true,
    targetUserId: 'admin-1',
    createdAt: '2026-04-13T10:00:00Z',
  },
];

export const MOCK_BLOCKED_ENTREPRENEURS = [
  {
    profileId: 401,
    userId: 'u4',
    email: 'sara.blocked@test.ly',
    fullName: 'Sara Khalil',
    companyName: 'Green Build Libya',
    deletedProjectsCount: 2,
    entrepreneurBlockedCount: 1,
    isBlocked: true,
    updatedAt: '2026-04-12T10:00:00Z',
  },
];

export const MOCK_STATS = {
  totalUsers: MOCK_USERS.length,
  totalProjects: MOCK_PROJECTS.length,
  totalInvestments: MOCK_INVESTMENTS.length,
  totalRevenue: 13500,
  activeProjects: 1,
  pendingProjects: 1,
  newUsersToday: 0,
  newUsersThisWeek: 2,
  totalTransactions: MOCK_PAYMENTS.length,
  successRate: 67,
};
