using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InvestlyFullAPI.Models;

// Represents a user account in the system
// Each property here maps to a column in the Users database table
public class User
{
    // Primary key - unique ID for every user, auto-generated by database
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int UserId { get; set; }

    // Email used for login and notifications. Every user must have one.
    [Required]
    [MaxLength(100)]
    public string Email { get; set; } = string.Empty;

    // NEVER store plain text passwords! This holds the BCrypt hash.
    [Required]
    [MaxLength(500)]
    public string PasswordHash { get; set; } = string.Empty;

    [Required]
    [MaxLength(50)]
    public string FirstName { get; set; } = string.Empty;

    [Required]
    [MaxLength(50)]
    public string LastName { get; set; } = string.Empty;

    public bool IsMale { get; set; }

    [MaxLength(50)]
    public string? NationalId { get; set; }

    public DateTime DateOfBirth { get; set; }

    [MaxLength(10)]
    [RegularExpression(@"^09\d{8}$")]
    public string? Phone { get; set; }

    [MaxLength(500)]
    public string? ProfilePictureUrl { get; set; }

    [MaxLength(50)]
    public string? BankAccountNumber { get; set; }

    // Soft delete: set to false instead of deleting the record
    public bool IsActive { get; set; } = true;

    // Email verification flag
    public bool EmailConfirmed { get; set; } = false;

    // Auto-set timestamps for tracking
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // Navigation: one user has MANY notifications (1-to-many)
    public ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    // Navigation: one user has MANY portfolios (1-to-many)
    public ICollection<Portfolio> Portfolios { get; set; } = new List<Portfolio>();
}
